# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170223_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='galleryItem',
            new_name='gallery_item',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='time',
        ),
        migrations.AddField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=True),
        ),
    ]
